unet:
  params:
    forward:
      - seq0
      - seq1
      - Return: mask

    seq0: #down stream
      save: True
      input: x
      output: y
      head:
        - BB.CC:
            C:
              in_channels: $unet_nch
              out_channels: $seq0.f[0]
              kernel_size: 3
              padding: 1
              bias: False
      supernode:
        - torch.nn.MaxPool2d:
            kernel_size: 2
        - BB.CC:
            C:
              in_channels: $seq0.f[i]
              out_channels: $seq0.f[i+1]
              kernel_size: 3
              padding: 1
              bias: False
      f:
        - 64
        - 128
        - 256
        - 512
        - 1024

    seq1: # up stream
      load: True
      input: y
      output: mask
      supernode:
        - torch.nn.ConvTranspose2d:
            in_channels: $seq0.f[-i-1]
            out_channels: $seq0.f[-i-1] // 2
            kernel_size: 2
            stride: 2
        - BB.Join:
            dim: 1
            needed:
              seq0_CC: $seq1.f[i]
        - BB.CC:
            C:
              in_channels: $seq0.f[-i-1]
              out_channels: $seq0.f[-i-2]
              kernel_size: 3
              padding: 1
              bias: False
      tail:
        - torch.nn.Conv2d:
            in_channels: $seq0.f[0]
            out_channels: $unet_outch
            kernel_size: 1
      f:
        - 3
        - 2
        - 1
        - 0
        - -1