unet_step:
  forward:
    - input: [z, randn, [3, 256, 256]]  # input z
    - seq0
    - Return: LOSS_VALUE
  
  seq0:
    input:
    output: LOSS_VALUE
    head:
      - BB.Self:
          fn: unet
          input: [[x, z]]
      - BB.Self:
          fn: unetLoss
          input: [[y], [t]]